### ISSUE TITLE
pytest 3.1.3 breaks tests

### ISSUE THREAD

**Issue by danstender** [eisensheng/pytest-catchlog#68]
We have the build resp. the tests breaking on _test_compat_camel_case_aliases_ since pytest update from 3.0.6 to 3.1.3, please see <https://ci.debian.net/packages/p/pytest-catchlog/unstable/amd64/>:
```
test_pytest_catchlog.py::test_compat_camel_case_aliases FAILED

=================================== FAILURES ===================================
________________________ test_compat_camel_case_aliases ________________________

testdir = <Testdir local('/tmp/pytest-of-aham/pytest-0/testdir/test_compat_camel_case_aliases0')>

    def test_compat_camel_case_aliases(testdir):
        testdir.makepyfile('''
            import logging
    
            def test_foo(caplog):
                caplog.setLevel(logging.INFO)
                logging.getLogger().debug('boo!')
    
                with caplog.atLevel(logging.WARNING):
                    logging.getLogger().info('catch me if you can')
            ''')
        result = testdir.runpytest()
        assert result.ret == 0
    
        py.test.raises(Exception, result.stdout.fnmatch_lines,
                       ['*- Captured *log call -*'])
    
        result = testdir.runpytest('-rw')
        assert result.ret == 0
        result.stdout.fnmatch_lines('''
            =*warning summary*=
            *WL1*test_compat_camel_case_aliases*caplog.setLevel()*deprecated*
            *WL1*test_compat_camel_case_aliases*caplog.atLevel()*deprecated*
>       ''')
E       Failed: nomatch: '=*warning summary*='
E           and: u'============================= test session starts =============================='
E           and: u'platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0'
E           and: u'rootdir: /tmp/pytest-of-aham/pytest-0/testdir/test_compat_camel_case_aliases0, inifile:'
E           and: u'plugins: catchlog-1.2.2'
E           and: u'collected 1 item'
E           and: u''
E           and: u'test_compat_camel_case_aliases.py .'
E           and: u''
E           and: u'=============================== warnings summary ==============================='
E           and: u'test_compat_camel_case_aliases.py::test_foo'
E           and: u"  'caplog.setLevel()' is deprecated, use 'caplog.set_level()' instead"
E           and: u"  'caplog.atLevel()' is deprecated, use 'caplog.at_level()' instead"
E           and: u''
E           and: u'-- Docs: http://doc.pytest.org/en/latest/warnings.html'
E           and: u'===================== 1 passed, 2 warnings in 0.00 seconds ====================='
E           and: u''
E       remains unmatched: '=*warning summary*='

/<<PKGBUILDDIR>>/test_pytest_catchlog.py:230: Failed
----------------------------- Captured stdout call -----------------------------
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /tmp/pytest-of-aham/pytest-0/testdir/test_compat_camel_case_aliases0, inifile:
plugins: catchlog-1.2.2
collected 1 item

test_compat_camel_case_aliases.py .

=============================== warnings summary ===============================
test_compat_camel_case_aliases.py::test_foo
  'caplog.setLevel()' is deprecated, use 'caplog.set_level()' instead
  'caplog.atLevel()' is deprecated, use 'caplog.at_level()' instead

-- Docs: http://doc.pytest.org/en/latest/warnings.html
===================== 1 passed, 2 warnings in 0.01 seconds =====================
============================= test session starts ==============================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /tmp/pytest-of-aham/pytest-0/testdir/test_compat_camel_case_aliases0, inifile:
plugins: catchlog-1.2.2
collected 1 item

test_compat_camel_case_aliases.py .

=============================== warnings summary ===============================
test_compat_camel_case_aliases.py::test_foo
  'caplog.setLevel()' is deprecated, use 'caplog.set_level()' instead
  'caplog.atLevel()' is deprecated, use 'caplog.at_level()' instead

-- Docs: http://doc.pytest.org/en/latest/warnings.html
===================== 1 passed, 2 warnings in 0.00 seconds =====================
------------------------------ Captured log call -------------------------------
test_compat_camel_case_aliases.py    5 DEBUG    boo!
test_compat_camel_case_aliases.py    8 INFO     catch me if you can
test_compat_camel_case_aliases.py    5 DEBUG    boo!
test_compat_camel_case_aliases.py    8 INFO     catch me if you can
!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
===================== 1 failed, 10 passed in 0.45 seconds ======================
E: pybuild pybuild:283: test: plugin custom failed with: exit code=2: python2.7 -m pytest -v -x
```
Thanks,
DS

**Comment by LocutusOfBorg** [comment]
Hello @The-Compiler, is it possible to have a fix against the latest stable release?

**Comment by The-Compiler** [comment]
@LocutusOfBorg Not by me, sorry. I lack the time currently.

**Comment by LocutusOfBorg** [comment]
sigh, I tried latest master and fails to test anyway with debian unstable :/

**Comment by The-Compiler** [comment]
That makes sense, as my PR is against the `development` branch, and also wasn't merged yet.

**Comment by LocutusOfBorg** [comment]
sorry, I meant ```development``` of course, the branch with the above commit

**Comment by LocutusOfBorg** [comment]
I can retry if needed

**Comment by LocutusOfBorg** [comment]
```
PYBUILD_SYSTEM=custom PYBUILD_TEST_ARGS="{interpreter} -m pytest -v -x" dh_auto_test
I: pybuild base:184: python2.7 -m pytest -v -x
============================= test session starts ==============================
platform linux2 -- Python 2.7.14rc1, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python2.7
cachedir: .cache
rootdir: /build/pytest-catchlog-1.2.2+git20170905, inifile:
plugins: catchlog-1.2.2
collecting ... INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 110, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 145, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 155, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 645, in perform_collect
INTERNALERROR>     items = self._perform_collect(args, genitems)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 682, in _perform_collect
INTERNALERROR>     self.items.extend(self.genitems(node))
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 824, in genitems
INTERNALERROR>     for x in self.genitems(subnode):
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 817, in genitems
INTERNALERROR>     node.ihook.pytest_itemcollected(item=node)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/build/pytest-catchlog-1.2.2+git20170905/tests/perf/conftest.py", line 84, in pytest_itemcollected
INTERNALERROR>     item.add_marker('_perf_test')
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 402, in add_marker
INTERNALERROR>     marker = getattr(MARK_GEN, marker)
INTERNALERROR>   File "/usr/lib/python2.7/dist-packages/_pytest/mark.py", line 261, in __getattr__
INTERNALERROR>     raise AttributeError("Marker name must NOT start with underscore")
INTERNALERROR> AttributeError: Marker name must NOT start with underscore

========================= no tests ran in 0.25 seconds =========================
```

**Comment by LocutusOfBorg** [comment]
sorry obviously wrong log:

```
writing manifest file 'pytest_catchlog.egg-info/SOURCES.txt'
Copying pytest_catchlog.egg-info to /build/pytest-catchlog-1.2.2+git20170905/debian/python3-pytest-catchlog/usr/lib/python3.5/dist-packages/pytest_catchlog-1.2.2.egg-info
Skipping SOURCES.txt
running install_scripts
PYBUILD_SYSTEM=custom PYBUILD_TEST_ARGS="{interpreter} -m pytest -v -x" dh_auto_test
I: pybuild base:184: python2.7 -m pytest -v -x
============================= test session starts ==============================
platform linux2 -- Python 2.7.14rc1, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- /usr/bin/python2.7
cachedir: .cache
rootdir: /build/pytest-catchlog-1.2.2+git20170905, inifile:
plugins: catchlog-1.2.2
collecting ... collected 29 items

tests/test_compat.py::test_camel_case_aliases PASSED
tests/test_compat.py::test_property_call PASSED
tests/test_compat.py::test_records_modification PASSED
tests/test_fixture.py::test_fixture_help PASSED
tests/test_fixture.py::test_change_level PASSED
tests/test_fixture.py::test_with_statement PASSED
tests/test_fixture.py::test_log_access PASSED
tests/test_fixture.py::test_record_tuples PASSED
tests/test_fixture.py::test_unicode PASSED
tests/test_fixture.py::test_clear PASSED
tests/test_fixture.py::test_special_warning_with_del_records_warning PASSED
tests/test_fixture.py::test_warning_with_setLevel PASSED
tests/test_reporting.py::test_nothing_logged PASSED
tests/test_reporting.py::test_messages_logged PASSED
tests/test_reporting.py::test_setup_logging PASSED
tests/test_reporting.py::test_teardown_logging PASSED
tests/test_reporting.py::test_disable_log_capturing PASSED
tests/test_reporting.py::test_disable_log_capturing_ini PASSED
tests/test_reporting.py::test_log_cli_default_level PASSED
tests/test_reporting.py::test_log_cli_level PASSED
tests/test_reporting.py::test_log_cli_ini_level PASSED
tests/test_reporting.py::test_log_file_cli PASSED
tests/test_reporting.py::test_log_file_cli_level PASSED
tests/test_reporting.py::test_log_file_ini PASSED
tests/test_reporting.py::test_log_file_ini_level PASSED
tests/perf/test_perf_run.py::test_perf_run[default] ERROR

!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/pytest.py", line 73, in <module>
    raise SystemExit(pytest.main())
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 58, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 139, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib/python2.7/dist-packages/_pytest/main.py", line 133, in wrap_session
    exitstatus=session.exitstatus)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
    wrap_controller.send(call_outcome)
  File "/usr/lib/python2.7/dist-packages/_pytest/terminal.py", line 413, in pytest_sessionfinish
    exitstatus=exitstatus)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib/python2.7/dist-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/build/pytest-catchlog-1.2.2+git20170905/tests/perf/conftest.py", line 115, in pytest_terminal_summary
    handle_perf_graph(config, terminalreporter)
  File "/build/pytest-catchlog-1.2.2+git20170905/tests/perf/conftest.py", line 119, in handle_perf_graph
    bench_storage = config.getoption('--benchmark-storage')
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 1238, in getoption
    raise ValueError("no option named %r" % (name,))
ValueError: no option named '--benchmark-storage'
E: pybuild pybuild:283: test: plugin custom failed with: exit code=1: python2.7 -m pytest -v -x
dh_auto_test: pybuild --test --test-pytest -i python{version} -p 2.7 returned exit code 13
```

**Comment by The-Compiler** [comment]
You'll need the [necessary dependencies installed](https://github.com/eisensheng/pytest-catchlog/blob/develop/tox.ini) to run the testsuite.

**Comment by LocutusOfBorg** [comment]
I have everything except pygaljs (not available in unstable)

**Comment by LocutusOfBorg** [comment]
I installed pygaljs with pip/pip3 and failed in the same way
```
    bench_storage = config.getoption('--benchmark-storage')
  File "/usr/lib/python2.7/dist-packages/_pytest/config.py", line 1238, in getoption
    raise ValueError("no option named %r" % (name,))
```
this smells to me like a mismatch in some versions

**Comment by The-Compiler** [comment]
Do you have pytest-benchmark 3.0.0 or newer?

**Comment by LocutusOfBorg** [comment]
yes, 3.0.0 https://packages.qa.debian.org/p/python-pytest-benchmark.html

**Comment by The-Compiler** [comment]
Since this was fixed in `development`, and the pytest-catchlog plugin (the `development` branch) was merged into the pytest core, this probably isn't applicable anymore.
